### ISSUE TITLE
Tracking ticket: Shell flags/`set` builtin

### ISSUE THREAD

**Issue by hawkw** [mgattozzi/ysh#23]
- [ ] determine what flags to support
- [ ] parse flags passed to the shell binary (i mainly expect this to be used with shebangs but i guess you could also set your login shell to `ysh -xyz`)
- [ ] add `set` builtin so scripts can set ysh flags
  - this implies that we should design the way flags are stored so that they can be mutated...
- [ ] implement flag behaviours (will require their own tickets)
